#!/usr/bin/perl -CS
$VERSION = 1.00;

=head1 NAME

dd_dump

=head1 DESCRIPTION

dd_dump dumps the contents of an AWS DynamoDB table to a JSON file.

=head1 USAGE

 dd_dump [OPTIONS]... [TABLE NAME]
 Options:
   -h,  --help        This help text
   -V,  --version     Show version number and quit

=cut

use v5.016;
use strict;
use warnings;
use utf8;
use constant TRUE => 1;
use constant FALSE => 0;

use lib qw( /opt/lib/site_perl );
use SitemasonPl::Common;
use SitemasonPl::CLI qw(mark print_object);
use SitemasonPl::Database::DynamoDB;


my $self = new();
$self || exit;

my @preinputs = @ARGV;


$self->{dd} = SitemasonPl::Database::DynamoDB->new;
my $tables = $self->{dd}->list_tables;
my $table = $self->{cli}->get_menu_answer($tables, "Choose a table to dump", { inputs => \@preinputs }) || exit;
my $ts = get_filename_utc_minute;

$self->{cli}->body("Dumping $table to $table-$ts.json");
my $records = $self->{dd}->scan($table);
my $json = make_json($records);
my $newpath = write_file("$table.json", $json, {
	add_date		=> TRUE,
	make_dirs		=> FALSE,
	overwrite		=> TRUE,
	print_errors	=> TRUE,
});




sub new {
	my %arg = @_;
	my $self = {};
	bless $self;
	
	$self->{cli} = SitemasonPl::CLI->new(
		exit_if_running		=> FALSE,
		commandline_args	=> []
	);
	
	return $self;
}

