#!/usr/bin/perl -CS
$VERSION = 1.00;

=head1 NAME

dd_import

=head1 DESCRIPTION

dd_import imports the contents of a JSON file into an AWS DynamoDB table.

=head1 USAGE

 dd_dump [OPTIONS]... [FILENAME]
 Options:
   -h,  --help        This help text
   -V,  --version     Show version number and quit

=cut

use v5.016;
use strict;
use warnings;
use utf8;
use constant TRUE => 1;
use constant FALSE => 0;

use lib qw( /opt/lib/site_perl );
use SitemasonPl::Common;
use SitemasonPl::CLI qw(mark print_object);
use SitemasonPl::Database::DynamoDB;


my $self = new();
$self || exit;

my $filename = shift;
my @preinputs = @ARGV;

if (!$filename) { $self->{cli}->error("A filename is required"); }
if (!-e $filename) { $self->{cli}->error("$filename not found"); }

$self->{dd} = SitemasonPl::Database::DynamoDB->new;
my $tables = $self->{dd}->list_tables;
my $table = $self->{cli}->get_menu_answer($tables, "Choose a table in which to import", { inputs => \@preinputs }) || exit;

$self->{cli}->body("Importing $filename into $table");
my $json = read_file($filename);
my $records = parse_json($json);

foreach my $record (@{$records}) {
	$self->{dd}->put_item($table, $record);
}


sub new {
	my %arg = @_;
	my $self = {};
	bless $self;
	
	$self->{cli} = SitemasonPl::CLI->new(
		exit_if_running		=> FALSE,
		commandline_args	=> []
	);
	
	return $self;
}

